// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {etcdtree} from '../models';

export function Model(arg1:etcdtree.Root):Promise<void>;

export function StartService(arg1:string):Promise<Error>;
