// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Model(arg1) {
  return window['go']['listwatcher']['Service']['Model'](arg1);
}

export function StartService(arg1) {
  return window['go']['listwatcher']['Service']['StartService'](arg1);
}
